---

# define these vars:
#  mongodb_version: '5.0'
#  mongodb_version_min: '5.0.17'
#  mongodb_user: 'mongodb'
#  mongodb_user_id: '1200'
#  mongodb_path_data: '/var/local/lib/mongodb'

- name: MongoDB | Vars
  ansible.builtin.set_fact:
    mongodb_path_build: '/etc/containers/build_mongodb'
    mongodb_compose_file: '/etc/containers/mongodb.yml'

- name: MongoDB | Adding service-user
  ansible.builtin.user:
    name: "{{ mongodb_user }}"
    uid: "{{ mongodb_user_id }}"

- name: MongoDB | Creating build-directory
  ansible.builtin.file:
    path: "{{ mongodb_path_build }}"
    state: directory
    mode: 0750
    owner: 'root'
    group: 'docker'

- name: MongoDB | Download Build-Files
  ansible.builtin.unarchive:
    src: 'https://github.com/docker-library/mongo/archive/refs/heads/master.zip'
    remote_src: true
    dest: "{{ mongodb_path_build }}/"
    mode: 0750
    owner: 'root'
    group: 'docker'

- name: MongoDB | Patch Build-Files (UID/GID/VERSION)
  ansible.builtin.replace:
    path: "{{ mongodb_path_build }}"
    regexp: "{{ item.s }}"
    replace: "{{ item.r }}"
  with_items:
    - {p: "mongodb/mongo-master/{{ mongodb_version }}/Dockerfile", s: ' 999 ', r: " {{ mongodb_user_id }} "}
    - {p: "mongodb/mongo-master/{{ mongodb_version }}/Dockerfile", s: '^ENV MONGO_VERSION.*$', r: "ENV MONGO_VERSION {{ mongodb_version_min }}"}
    - {p: "mongodb/mongo-master/{{ mongodb_version }}/Dockerfile", s: ' keyserver.ubuntu.com ', r: ' hkp://keyserver.ubuntu.com:80 '}
    - {p: "mongodb/mongo-master/{{ mongodb_version }}/Dockerfile",
       s: 'COPY docker-entrypoint\.sh \/usr\/local\/bin\/\nENTRYPOINT \["docker-entrypoint\.sh"\]',
       r: 'COPY docker-entrypoint.sh /usr/local/bin/\nRUN chmod 775 /usr/local/bin/docker-entrypoint.sh\nENTRYPOINT ["docker-entrypoint.sh"]'}

- name: MongoDB | Copying docker-compose config
  ansible.builtin.templates:
    src: 'Rebuild_docker-compose.yml'
    dest: "{{ mongodb_compose_file }}"
    mode: 0640
    owner: 'root'
    group: 'docker'

# NOTE: could use community.docker.docker_compose
- name: MongoDB | Running docker-compose & building image locally
  ansible.builtin.command: "docker-compose -f {{ mongodb_compose_file }} up"
